using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace The_Kingdom_of_Algorithmia___2024__.Quest_01
{
    internal class Quest01
    {
        private Dictionary<char, int> PotionCost = new() { { 'A', 0 }, { 'B', 1 }, { 'C', 3 } };

        public void Solve()
        {
            var exampleInput = "ABBAC";
            var input = "ACCACCBCCBACACCBBABACBABBAAABAACAABCACACCACABACAABBACBCCBCCBCBAABABCCBAACCABBCBBABBBBBCBBBAAACCBAAABACCAACCCABCCACCABBCCBCCBCBAABCBCBCABABAACABACBCACACCABCBCCABAACACBBCBABCBBBCBBBCCACBACBCCBAABBBCBCABCABABBBBCBAABACBBBABACACCACCABACCCCBBBABBBCBCBABAAACCCAACBBCBBCCAACBCAABCCBAABCAACCCBBACCCAABCBCABBABABCCACABBCBCBBCBACAACCBBCCCCBBABCCCABCACABACCCCBBABCABBABBCCCCCAACACBACBACAABBAACBAACACBBCCBCCCCCAACACCBBABACBABBAABACCCCCCBBCBCACBCAAACBBAABBCCCCAABBBCAAACABAAAABBAAAACBBAABBABABAAAAABABCABCABABCCABCACCAAACAABABACABCCBAACCCBAACAABACABABCBAABBACACCABAABBBAACCCBACCCACBBBCABBCCACCBCBBBBBACCACACABAAABBCACAACCBABBCCBACBBAABBACAABCBCBCBBAABACCCCCBBBCAAACAACBCBCCBBCABAAAAACBBABCBBAAAACBABBBCAACCACBBAAACBACACCABBCABACCBBCCBBCBBAAABCACBBBCCBACABBBCBBACCBBACCBAABCAABCBCAABABAACAACAABACBBCCCBAACACBAACAABCCBCBACCABABBCCCBAAACCABBCBACCACBBABCBAAAABBBCBBCAABABAACBAAACCACBBCABABCCCACAAABABBBCBAACAABBBBABCBBACABCAACACCBAABBBAAACBCBAABAAABABBCBBBABABABBCBBBBCACCACBAAABBABBBBCABCBAABACBBABCCABACBCCBACACBCAA";

            var potionCount = 0;

            foreach (char c in input)
            {
                potionCount += PotionCost[c];
                Console.WriteLine(c);
            }

            Console.WriteLine("Total Potion Count is : {0}", potionCount);
        }
    }
}